### ISSUE TITLE
Access Token Error 404

### ISSUE THREAD

**Issue by DillonW23** [ibm-early-programs/node-red-contrib-watson-machine-learning#16]
I have tried to add an access key but it returns an error in the debug tab "Access Token Error 404". Where exactly can I get the correct access key? I have tried to add a platform api key in the ibm cloud, but it didn't work for accessing the machine learning. I also added service credentials in the machine learning service but it doesn't show access key anywhere in there. Any help is appreciated

**Comment by chughts** [comment]
In the current release the Access Token isn't actually required, it was added as a place holder, but never used. The dialog has a bug in that it is a mandated field, so any value works. That you are getting a 404 error could be related to #17 , but as the existing authentication mechanism works until the 30th May. This is more likely to be related to the username / password that you are supplying. You need to have instantiated a machine learning instance, and created credentials for the service.

**Comment by chughts** [comment]
Fixed in 0.1.0
