### ISSUE TITLE
Authentication Mechanism Needs updating

### ISSUE THREAD

**Issue by chughts** [ibm-early-programs/node-red-contrib-watson-machine-learning#17]
The existing authentication mechanism has been deprecated, and a new IAM Key mechanism is required. 

https://www.ibm.com/blogs/bluemix/2019/04/announcing-the-deprecation-of-the-watson-machine-learning-json-token-authentication-service/

**Comment by Nishchith007** [comment]
What is the way forward. How can we connect from node red now. Please advise. I just started today to work on Watson, apologies if my question is silly.

**Comment by chughts** [comment]
I am happy to accept a pull request with the necessary modifications.

**Comment by Nishchith007** [comment]
Sorry, not sure how can I help here. Really a newbie to GIT as well. Is it impossible to connect from NodeRED at this stage? Please help.

**Comment by chughts** [comment]
What is it that you are trying to do?

**Comment by Nishchith007** [comment]
Sir, I have created a model ( Binary Classification ) in IBM Watson studio. I have loaded the data set and run the experiment. Everything is good till there.

Now, I have imported a flow from github to create a Node-RED flow. 

https://github.com/ibm-early-programs/animal-sounds/tree/master/noderedflows 
predictionflow.json

Inside the flow, we have RunPrediction node. In that we have "WML Connection" where I need to give username , password , hostURL and Instance ID to connect to model. 

I have Host URL and Instance ID. I got it from IBM Cloud --> Services --> Service Credentials.

But it has below data : I dont see username and password. Please help me to configure "WML Connection" in RunPrediction node.

{
  "apikey": "LcmXFAhn2QcnKOnbqkuEVGC",
  "iam_apikey_description": "Auto-generated for key 5f555047-f7730",
  "iam_apikey_name": "wdp-writer",
  "iam_role_crn": "crn:v1:bluemix:pr",
  "iam_serviceid_crn": "crn:v1:bluemix:public:iam-identity::a/bc1fe4f02a7c",
  "instance_id": "7a399080-2b6b-45da-ad4",
  "url": "https://us-south.ml.cloud.ibm.com"
}

Note : I have manipulated apikey and other details for security reasons.

Thank you very much in advance.

**Comment by chughts** [comment]
You shouldn't share your API key like that.

It looks like you need a fix to this issue. Its on my backlog of issues to fix, but I am a bit bogged down with higher priority work. If there is anyone who has time to resolve the issue, then I am happy to check the fix and accept a pull request.

**Comment by chughts** [comment]
Fixed in 0.1.0
